apiVersion: v1
kind: ConfigMap
metadata:
  name: governor-env
data:
  ENV: DEV
  PORT: "8080"
  DB_HOST: governor-postgres
  DB_PORT: "5435"
  DB_USER: governor
  DB_PASSWORD: password
  DB_NAME: governor
  ORIGIN_SERVICE: governor
  POSTGRES_USER: governor
  POSTGRES_PASSWORD: password
  POSTGRES_DB: governor
  REDIS_HOST: governor-redis
  REDIS_PORT: "6349"
  REDIS_PASSWORD: password
  UASAM_URL: http://host.docker.internal:8002
  FORGE_URL: http://host.docker.internal:8010
  GOVERNOR_URL: http://host.docker.internal:8008
  DOCKER_USERNAME: anirudhrv1234
  DOCKER_REPOSITORY: anirudhrv1234
  DOCKER_PASSWORD: TF3dE5aay64,HnW
  DOCKER_SERVER_ADDRESS: https://index.docker.io/v1/
  DOCKER_BUILDKIT: "1"
  FORGE_API_KEY: passkey_forge
  KAFKA_BROKERS: governor-kafka:9092
  KAFKA_TIMEOUT: "30"
  KAFKA_GROUP_ID: governor-consumer-group
  KAFKA_TOPIC: topic.governor.job
