services:
  orchestrator:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile-local
    container_name: orchestrator-container
    ports:
      - "8006:8080"
    env_file:
      - ../env/local-env.env
    volumes:
      - ..:/app
    restart: unless-stopped
    depends_on:
      - orchestrator-postgres
      - orchestrator-redis

  orchestrator-postgres:
    image: postgres:17
    container_name: orchestrator-postgres-container
    env_file:
      - ../env/local-env.env
    volumes:
      - orchestrator_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

  orchestrator-redis:
    image: redis:7
    container_name: orchestrator-redis-container
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6399:6379"

volumes:
  orchestrator_pgdata:
