apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: app
build:
  artifacts:
    - image: uasam
      context: Backend/uasam
      docker:
        dockerfile: dockerfiles/Dockerfile-local
      sync:
        manual:
          - src: "**/*.go"
            dest: .
          - src: "**/*.tmpl"
            dest: .
          - src: ".air.toml"
            dest: .
    - image: governor
      context: Backend/governor
      docker:
        dockerfile: dockerfiles/Dockerfile-local
      sync:
        manual:
          - src: "**/*.go"
            dest: .
          - src: "**/*.tmpl"
            dest: .
          - src: ".air.toml"
            dest: .
    - image: forge
      context: Backend/forge
      docker:
        dockerfile: dockerfiles/Dockerfile-local
      sync:
        manual:
          - src: "**/*.go"
            dest: .
          - src: "**/*.tmpl"
            dest: .
          - src: ".air.toml"
            dest: .
    - image: secretsmanager
      context: Backend/secretsmanager
      docker:
        dockerfile: dockerfiles/Dockerfile-local
      sync:
        manual:
          - src: "**/*.go"
            dest: .
          - src: "**/*.tmpl"
            dest: .
          - src: ".air.toml"
            dest: .
    - image: algonexus
      context: Backend/algonexus
      docker:
        dockerfile: dockerfiles/Dockerfile-local
      sync:
        manual:
          - src: "**/*.go"
            dest: .
          - src: "**/*.tmpl"
            dest: .
          - src: ".air.toml"
            dest: .
  local:
    push: false
    useDockerCLI: true

manifests:
  rawYaml:
    # UASAM
    - Kubernetes/uasam/configmap.yaml
    - Kubernetes/uasam/postgres.yaml
    - Kubernetes/uasam/redis.yaml
    - Kubernetes/uasam/deployment.yaml
    - Kubernetes/uasam/service.yaml

    # Governor
    - Kubernetes/governor/configmap.yaml
    - Kubernetes/governor/postgres.yaml
    - Kubernetes/governor/redis.yaml
    - Kubernetes/governor/zookeeper.yaml
    - Kubernetes/governor/kafka.yaml
    - Kubernetes/governor/deployment.yaml
    - Kubernetes/governor/service.yaml
    - Kubernetes/governor/namespace.yaml
    - Kubernetes/governor/job-role.yaml
    - Kubernetes/governor/job-role-binding.yaml

    # Forge
    - Kubernetes/forge/configmap.yaml
    - Kubernetes/forge/postgres.yaml
    - Kubernetes/forge/redis.yaml
    - Kubernetes/forge/deployment.yaml
    - Kubernetes/forge/service.yaml

    # SecretsManager
    - Kubernetes/secretsmanager/configmap.yaml
    - Kubernetes/secretsmanager/postgres.yaml
    - Kubernetes/secretsmanager/redis.yaml
    - Kubernetes/secretsmanager/deployment.yaml
    - Kubernetes/secretsmanager/service.yaml

    #AlgoNexus
    - Kubernetes/algonexus/configmap.yaml
    - Kubernetes/algonexus/postgres.yaml
    - Kubernetes/algonexus/redis.yaml
    - Kubernetes/algonexus/zookeeper.yaml
    - Kubernetes/algonexus/kafka.yaml
    - Kubernetes/algonexus/clickhouse.yaml
    - Kubernetes/algonexus/tabix.yaml
    - Kubernetes/algonexus/deployment.yaml
    - Kubernetes/algonexus/service.yaml

    #Kong
    - Kubernetes/gateway/algonexus-ingress.yaml
    - Kubernetes/gateway/algonexus-hostname-service.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: uasam-service
    namespace: default
    port: 8002
    localPort: 8002
  - resourceType: service
    resourceName: governor-service
    namespace: default
    port: 8008
    localPort: 8008
  - resourceType: service
    resourceName: forge-service
    namespace: default
    port: 8010
    localPort: 8010
  - resourceType: service
    resourceName: secretsmanager-service
    namespace: default
    port: 8004
    localPort: 8004
  - resourceType: service
    resourceName: algonexus-service
    namespace: default
    port: 8081
    localPort: 8081
