apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: algonexus-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: algonexus-postgres
spec:
  selector:
    app: algonexus-postgres
  ports:
    - protocol: TCP
      port: 5425
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algonexus-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algonexus-postgres
  template:
    metadata:
      labels:
        app: algonexus-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: algonexus-env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: algonexus-pgdata
      volumes:
        - name: algonexus-pgdata
          persistentVolumeClaim:
            claimName: algonexus-pgdata
