// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/algorithm/python/build/": {
            "post": {
                "description": "Accepts a user ID, script ID, and script URL to build and push the Python algorithm as a Docker image.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PythonBuilder"
                ],
                "summary": "Build and Push Python Algorithm",
                "parameters": [
                    {
                        "description": "Python Builder Request",
                        "name": "PythonBuilderRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PythonBuilderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User Algorithm Built and Pushed successfully",
                        "schema": {
                            "$ref": "#/definitions/models.PythonBuilderResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.PythonBuilderResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.PythonBuilderResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.PythonBuilderRequest": {
            "type": "object",
            "properties": {
                "scriptID": {
                    "type": "string"
                },
                "scriptURL": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "models.PythonBuilderResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
