definitions:
  models.PythonBuilderRequest:
    properties:
      scriptID:
        type: string
      scriptURL:
        type: string
      userID:
        type: string
    type: object
  models.PythonBuilderResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/algorithm/python/build/:
    post:
      consumes:
      - application/json
      description: Accepts a user ID, script ID, and script URL to build and push
        the Python algorithm as a Docker image.
      parameters:
      - description: Python Builder Request
        in: body
        name: PythonBuilderRequest
        required: true
        schema:
          $ref: '#/definitions/models.PythonBuilderRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User Algorithm Built and Pushed successfully
          schema:
            $ref: '#/definitions/models.PythonBuilderResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/models.PythonBuilderResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.PythonBuilderResponse'
      summary: Build and Push Python Algorithm
      tags:
      - PythonBuilder
swagger: "2.0"
