// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/user/sign-up/init/": {
            "post": {
                "description": "Initiates user sign-up by checking if the user exists and sending OTP for verification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Initialize Sign Up",
                "parameters": [
                    {
                        "description": "Sign Up Init Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OTP verification initiated",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInitResponse"
                        }
                    },
                    "400": {
                        "description": "User already exists or invalid payload",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInitResponse"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpInitResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/sign-up/verify-otp/": {
            "post": {
                "description": "Verifies the OTP and creates the user account if valid.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Verify OTP and Sign Up User",
                "parameters": [
                    {
                        "description": "Verify OTP Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SignUpVerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpVerifyOTPResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpVerifyOTPResponse"
                        }
                    },
                    "401": {
                        "description": "Wrong OTP",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpVerifyOTPResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.SignUpVerifyOTPResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.SignUpInitRequest": {
            "type": "object",
            "properties": {
                "emailId": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "models.SignUpInitResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.SignUpVerifyOTPRequest": {
            "type": "object",
            "properties": {
                "emailId": {
                    "type": "string"
                },
                "otp": {
                    "type": "string"
                }
            }
        },
        "models.SignUpVerifyOTPResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.UserReturnObject"
                }
            }
        },
        "models.UserReturnObject": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "emailID": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "middleName": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
