apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forge
  template:
    metadata:
      labels:
        app: forge
    spec:
      containers:
        - name: forge
          image: forge
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: forge-env
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
