services:
  cortex-service:
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../env/local-env.env
    restart: unless-stopped
    depends_on:
      - cortex-postgres

  cortex-postgres:
    image: postgres:17
    container_name: cortex-postgres-container
    env_file:
      - ../env/local-env.env
    volumes:
      - cortex_pgdata:/var/lib/postgresql/data
    ports:
      - "5425:5432"
    restart: unless-stopped

  cortex-redis:
    image: redis:7
    container_name: cortex-redis-container
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6310:6379"

volumes:
  cortex_pgdata:
