// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/algorithm/start/": {
            "post": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Initiates the scheduled execution of a user algorithm based on the provided algorithm ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Stops the user algorithm using a cron schedule",
                "parameters": [
                    {
                        "description": "Stop Algorithm Cron Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StopUserAlgorithmRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StopUserAlgorithmResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.StopUserAlgorithmResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.StopUserAlgorithmResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/": {
            "get": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Retrieves the list of all algorithms associated with the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Get all user algorithms",
                "responses": {
                    "200": {
                        "description": "User algorithms retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllUserAlgorithmsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllUserAlgorithmsResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves a specific user algorithm by its ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Get user algorithm details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Algorithm ID",
                        "name": "algorithm_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Algorithm fetched successfully",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserAlgorithmResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid algorithm_id",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserAlgorithmResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserAlgorithmResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/python/upload/": {
            "post": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Uploads a script file and creates a new user algorithm associated with the authenticated user.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Create a user algorithm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script Name",
                        "name": "script_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Python script file",
                        "name": "script",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Algorithm created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or file upload failed",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/schedule/": {
            "post": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Updates the cron schedule for an existing user algorithm belonging to the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Update user algorithm cron schedule",
                "parameters": [
                    {
                        "description": "Cron schedule update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cron schedule updated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/schedule/cancel/": {
            "post": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Cancels the start and end cron jobs of a specific user algorithm, if the algorithm belongs to the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Cancel cron schedule for a user's algorithm",
                "parameters": [
                    {
                        "description": "Algorithm cancellation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CancelUserAlgorithmCronScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully canceled algorithm schedule",
                        "schema": {
                            "$ref": "#/definitions/models.CancelUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.CancelUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error during schedule cancellation",
                        "schema": {
                            "$ref": "#/definitions/models.CancelUserAlgorithmCronScheduleResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CancelUserAlgorithmCronScheduleRequest": {
            "type": "object",
            "properties": {
                "algorithmID": {
                    "type": "string"
                }
            }
        },
        "models.CancelUserAlgorithmCronScheduleResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithm": {
                    "$ref": "#/definitions/models.UserAlgorithm"
                }
            }
        },
        "models.GetAllUserAlgorithmsResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserAlgorithmInfo"
                    }
                }
            }
        },
        "models.GetUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithm": {
                    "$ref": "#/definitions/models.UserAlgorithmInfo"
                }
            }
        },
        "models.OrderDomain": {
            "type": "integer",
            "enum": [
                0,
                1,
                2
            ],
            "x-enum-varnames": [
                "Backtest",
                "PaperTrading",
                "LiveTrading"
            ]
        },
        "models.StartUserAlgorithmRequest": {
            "type": "object",
            "required": [
                "algorithmID",
                "end_time",
                "frequency",
                "market",
                "portfolio_size",
                "start_time",
                "symbol"
            ],
            "properties": {
                "algorithmID": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "frequency": {
                    "type": "integer"
                },
                "market": {
                    "type": "string"
                },
                "portfolio_size": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "models.StartUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.StopUserAlgorithmRequest": {
            "type": "object",
            "properties": {
                "algorithmID": {
                    "type": "string"
                }
            }
        },
        "models.StopUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserAlgorithmCronScheduleRequest": {
            "type": "object",
            "properties": {
                "algorithmID": {
                    "type": "string"
                },
                "endCronSchedule": {
                    "type": "string"
                },
                "startCronSchedule": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserAlgorithmCronScheduleResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.UserAlgorithm": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "endCronSchedule": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "orderDomain": {
                    "$ref": "#/definitions/models.OrderDomain"
                },
                "scriptName": {
                    "type": "string"
                },
                "scriptURL": {
                    "type": "string"
                },
                "startCronSchedule": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "models.UserAlgorithmInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "endCronSchedule": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "order_domain": {
                    "$ref": "#/definitions/models.OrderDomain"
                },
                "scriptName": {
                    "type": "string"
                },
                "scriptUrl": {
                    "type": "string"
                },
                "startCronSchedule": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
