// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/user/algorithm/": {
            "get": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Retrieves the list of all algorithms associated with the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Get all user algorithms",
                "responses": {
                    "200": {
                        "description": "User algorithms retrieved successfully",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllUserAlgorithmsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.GetAllUserAlgorithmsResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/python/upload/": {
            "post": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Uploads a script file and creates a new user algorithm associated with the authenticated user.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Create a user algorithm",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Script Name",
                        "name": "script_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Python script file",
                        "name": "script",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Algorithm created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or file upload failed",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserAlgorithmResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/schedule/": {
            "put": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Updates the cron schedule for an existing user algorithm belonging to the authenticated user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Update user algorithm cron schedule",
                "parameters": [
                    {
                        "description": "Cron schedule update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cron schedule updated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserAlgorithmCronScheduleResponse"
                        }
                    }
                }
            }
        },
        "/v1/user/algorithm/{id}": {
            "get": {
                "security": [
                    {
                        "USER_TOKEN": []
                    }
                ],
                "description": "Retrieves a specific user algorithm for the authenticated user using the algorithm ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserAlgorithm"
                ],
                "summary": "Get user algorithm by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Algorithm ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Algorithm fetched successfully",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserAlgorithmResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to fetch user algorithm",
                        "schema": {
                            "$ref": "#/definitions/models.GetUserAlgorithmResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreateUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithm": {
                    "$ref": "#/definitions/models.UserAlgorithm"
                }
            }
        },
        "models.GetAllUserAlgorithmsResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserAlgorithmInfo"
                    }
                }
            }
        },
        "models.GetUserAlgorithmResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                },
                "user_algorithm": {
                    "$ref": "#/definitions/models.UserAlgorithmInfo"
                }
            }
        },
        "models.UpdateUserAlgorithmCronScheduleRequest": {
            "type": "object",
            "properties": {
                "algorithmID": {
                    "type": "string"
                },
                "cronSchedule": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserAlgorithmCronScheduleResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                },
                "statusDescription": {
                    "type": "string"
                }
            }
        },
        "models.UserAlgorithm": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "cronSchedule": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "scriptName": {
                    "type": "string"
                },
                "scriptURL": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "models.UserAlgorithmInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "cronSchedule": {
                    "type": "string"
                },
                "scriptID": {
                    "type": "string"
                },
                "scriptName": {
                    "type": "string"
                },
                "script_url": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
