definitions:
  models.CreateUserAlgorithmResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
      user_algorithm:
        $ref: '#/definitions/models.UserAlgorithm'
    type: object
  models.GetAllUserAlgorithmsResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
      user_algorithms:
        items:
          $ref: '#/definitions/models.UserAlgorithmInfo'
        type: array
    type: object
  models.GetUserAlgorithmResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
      user_algorithm:
        $ref: '#/definitions/models.UserAlgorithmInfo'
    type: object
  models.OrderDomain:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - Backtest
    - PaperTrading
    - LiveTrading
  models.UpdateUserAlgorithmCronScheduleRequest:
    properties:
      algorithmID:
        type: string
      endCronSchedule:
        type: string
      startCronSchedule:
        type: string
    type: object
  models.UpdateUserAlgorithmCronScheduleResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
    type: object
  models.UserAlgorithm:
    properties:
      createdAt:
        type: string
      endCronSchedule:
        type: string
      id:
        type: string
      orderDomain:
        $ref: '#/definitions/models.OrderDomain'
      scriptName:
        type: string
      scriptURL:
        type: string
      startCronSchedule:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
    type: object
  models.UserAlgorithmInfo:
    properties:
      created_at:
        type: string
      endCronSchedule:
        type: string
      id:
        type: string
      order_domain:
        $ref: '#/definitions/models.OrderDomain'
      scriptName:
        type: string
      scriptUrl:
        type: string
      startCronSchedule:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/user/algorithm/:
    get:
      description: Retrieves the list of all algorithms associated with the authenticated
        user.
      produces:
      - application/json
      responses:
        "200":
          description: User algorithms retrieved successfully
          schema:
            $ref: '#/definitions/models.GetAllUserAlgorithmsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.GetAllUserAlgorithmsResponse'
      security:
      - USER_TOKEN: []
      summary: Get all user algorithms
      tags:
      - UserAlgorithm
  /v1/user/algorithm/{id}:
    get:
      description: Retrieves a specific user algorithm for the authenticated user
        using the algorithm ID.
      parameters:
      - description: Algorithm ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Algorithm fetched successfully
          schema:
            $ref: '#/definitions/models.GetUserAlgorithmResponse'
        "500":
          description: Failed to fetch user algorithm
          schema:
            $ref: '#/definitions/models.GetUserAlgorithmResponse'
      security:
      - USER_TOKEN: []
      summary: Get user algorithm by ID
      tags:
      - UserAlgorithm
  /v1/user/algorithm/python/upload/:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a script file and creates a new user algorithm associated
        with the authenticated user.
      parameters:
      - description: Script Name
        in: formData
        name: script_name
        required: true
        type: string
      - description: Python script file
        in: formData
        name: script
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Algorithm created successfully
          schema:
            $ref: '#/definitions/models.CreateUserAlgorithmResponse'
        "400":
          description: Invalid input or file upload failed
          schema:
            $ref: '#/definitions/models.CreateUserAlgorithmResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.CreateUserAlgorithmResponse'
      security:
      - USER_TOKEN: []
      summary: Create a user algorithm
      tags:
      - UserAlgorithm
  /v1/user/algorithm/schedule/:
    put:
      consumes:
      - application/json
      description: Updates the cron schedule for an existing user algorithm belonging
        to the authenticated user.
      parameters:
      - description: Cron schedule update payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserAlgorithmCronScheduleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Cron schedule updated successfully
          schema:
            $ref: '#/definitions/models.UpdateUserAlgorithmCronScheduleResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/models.UpdateUserAlgorithmCronScheduleResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.UpdateUserAlgorithmCronScheduleResponse'
      security:
      - USER_TOKEN: []
      summary: Update user algorithm cron schedule
      tags:
      - UserAlgorithm
swagger: "2.0"
