definitions:
  models.UserSecret:
    properties:
      createdAt:
        type: string
      id:
        type: string
      key:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
      value:
        type: string
    type: object
  models.UserSecretsGetResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
      userSecret:
        $ref: '#/definitions/models.UserSecret'
    type: object
  models.UserSecretsSetRequest:
    properties:
      key:
        type: string
      value:
        type: string
    required:
    - key
    - value
    type: object
  models.UserSecretsSetResponse:
    properties:
      status:
        type: integer
      statusDescription:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/user/secrets/:
    get:
      consumes:
      - application/json
      description: Fetches a specific secret key-value pair for an authenticated user.
      parameters:
      - description: Secret key to fetch
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: User secret fetched successfully
          schema:
            $ref: '#/definitions/models.UserSecretsGetResponse'
        "400":
          description: Invalid request or missing user ID
          schema:
            $ref: '#/definitions/models.UserSecretsGetResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.UserSecretsGetResponse'
      security:
      - ApiKeyAuth: []
      summary: Get a user's secret
      tags:
      - UserSecrets
    post:
      consumes:
      - application/json
      description: Stores or updates a secret key-value pair for an authenticated
        user.
      parameters:
      - description: Secret key-value to set
        in: body
        name: userSecret
        required: true
        schema:
          $ref: '#/definitions/models.UserSecretsSetRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User secret set successfully
          schema:
            $ref: '#/definitions/models.UserSecretsSetResponse'
        "400":
          description: Invalid request or missing user ID
          schema:
            $ref: '#/definitions/models.UserSecretsSetResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/models.UserSecretsSetResponse'
      security:
      - ApiKeyAuth: []
      summary: Set a user's secret
      tags:
      - UserSecrets
swagger: "2.0"
