services:
  algorithms-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - "../env/local.env"
    expose:
      - "5432"
    ports:
      - "5432:5432"
  algorithms:
    build:
      context: "../"
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    env_file:
      - "../env/local.env"
    depends_on:
      - algorithms-db

volumes:
  postgres_data:
