package constants

import "os"

var UASAM_ENDPOINT = os.Getenv("UASAM_URL")
var API_AUTHENTICATION_ENDPOINT = UASAM_ENDPOINT + "/v1/microservice/authenticate/"
var USER_SCRIPT_AUTHENTICATION_ENDPOINT = UASAM_ENDPOINT + "/v1/microservice/user/authenticate/"
var AES256_32BYTE_ENCRYPTION_KEY = os.Getenv("AES256_32BYTE_ENCRYPTION_KEY")
var AES256_32BYTE_DETERMINISTIC_ENCRYPTION_KEY = os.Getenv("AES256_32BYTE_DETERMINISTIC_ENCRYPTION_KEY")
var USER_AUTHENTICATION_ENDPOINT = UASAM_ENDPOINT + "/v1/user/authenticate/"
