package constants

import "os"

var UASAM_ENDPOINT = os.Getenv("UASAM_URL")
var API_AUTHENTICATION_ENDPOINT = UASAM_ENDPOINT + "/v1/microservice/authenticate/"
var IP_LOCATION_API_ENDPOINT = os.Getenv("IP_LOCATION_API_ENDPOINT")
var AES256_32BYTE_ENCRYPTION_KEY = os.Getenv("AES256_32BYTE_ENCRYPTION_KEY")
var AES256_32BYTE_DETERMINISTIC_ENCRYPTION_KEY = os.Getenv("AES256_32BYTE_DETERMINISTIC_ENCRYPTION_KEY")
