services:
  governor:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile-local
    container_name: governor-container
    ports:
      - "8008:8080"
    env_file:
      - ../env/local-env.env
    volumes:
      - ..:/app
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - governor-postgres
      - governor-redis

  governor-postgres:
    image: postgres:17
    container_name: governor-postgres-container
    env_file:
      - ../env/local-env.env
    volumes:
      - governor_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

  governor-redis:
    image: redis:7
    container_name: governor-redis-container
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6349:6379"

  governor-zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: governor-zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  governor-kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: governor-kafka-container
    depends_on:
      - governor-zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: governor-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://governor-kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  governor_pgdata:
