services:
  governor:
    build:
      context: ..
    container_name: governor-container
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - "8008:8000"
    env_file:
      - ../env/local-env.env
    depends_on:
      - governor-postgres
    command: >
      sh -c "python manage.py migrate && gunicorn governor.wsgi:application --bind 0.0.0.0:8000"

  governor-postgres:
    image: postgres:17
    container_name: governor-postgres-container
    env_file:
      - ../env/local-env.env
    volumes:
      - governor_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: unless-stopped

volumes:
  governor_pgdata:
