apiVersion: v1
kind: ConfigMap
metadata:
  name: uasam-env
data:
  ENV: dev
  PORT: "8080"
  DB_HOST: uasam-postgres
  DB_PORT: "5432"
  DB_USER: uasam
  DB_PASSWORD: password
  DB_NAME: uasam
  OTP_ISSUER: zhuhana.com
  OTP_SKEW: "10"
  OTP_SECRETS_KEY_SUFFIX: otp_secret
  OTP_DURATION_IN_SECONDS: "300"
  USER_JWT_SECRET_KEY: SUPER_SECRET_KEY_WHOLE_INFRA_DEPENDS_ON_THIS
  USER_JWT_EXPIRATION_DAYS: "30"
  MICROSERVICES_JWT_SECRET_KEY: SUPER_SECRET_KEY_FOR_MICROSERVICES_JWT
  MICROSERVICES_JWT_EXPIRATION_DAYS: "1"
  RESET_PASSWORD_KEY_SUFFIX: reset_password
  RESET_PASSWORD_TOKEN_DURATION_IN_SECOND: "300"
  BREVO_API_KEY: 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
  IP_LOCATION_API_ENDPOINT: https://freeipapi.com/api/json/
  BREVO_SEND_EMAIL_API_ENDPOINT: https://api.brevo.com/v3/smtp/email/
  SENDER_EMAIL_NAME: Zhuhana
  SENDER_EMAIL_ID: noreply@zhuhana.com
  AES256_32BYTE_ENCRYPTION_KEY: your-32-byte-long-secret-key-her
  AES256_32BYTE_DETERMINISTIC_ENCRYPTION_KEY: your-32-byte-long-secret-key-her
  POSTGRES_USER: uasam
  POSTGRES_PASSWORD: password
  POSTGRES_DB: uasam
  REDIS_HOST: uasam-redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: password
  GOVERNOR_API_KEY: passkey_governor
  ORCHESTRATOR_API_KEY: passkey_orchestrator
  OUTBOUND_API_KEY: passkey_outbound
  UASAM_API_KEY: passkey_uasam
  SECRETS_MANAGER_API_KEY: passkey_secrets_manager
  FORGE_API_KEY: passkey_forge
  UASAM_URL: http://host.docker.internal:8002
  NEWS_API_KEY: pub_0448d9d30d294a92a1179330e059e9c1
  NEWS_API_ENDPOINT: https://newsdata.io/api/1/latest
