apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uasam-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: uasam-postgres
spec:
  selector:
    app: uasam-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uasam-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uasam-postgres
  template:
    metadata:
      labels:
        app: uasam-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: uasam-env
          volumeMounts:
            - mountPath: /var/lib/uasam/postgresql/data
              name: uasam-pgdata
      volumes:
        - name: uasam-pgdata
          persistentVolumeClaim:
            claimName: uasam-pgdata
