version: "3.9"

services:
  outbound:
    build: ..
    container_name: outbound-container
    ports:
      - "8000:8080"
    environment:
      - PORT=8080
    volumes:
      - .:/app
    restart: unless-stopped
