// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/marketdata/v1/stocks/all-tickers": {
            "get": {
                "description": "Fetches all tickers with an optional limit parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tickers"
                ],
                "summary": "Get all tickers",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of tickers to retrieve (default: 10)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of tickers",
                        "schema": {
                            "$ref": "#/definitions/stocks.AllTickersAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Error message",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "stocks.AllTickerStockInformation": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "cik": {
                    "type": "string"
                },
                "composite_figi": {
                    "type": "string"
                },
                "currency_name": {
                    "type": "string"
                },
                "last_updated_utc": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                },
                "market": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "primary_exchange": {
                    "type": "string"
                },
                "share_class_figi": {
                    "type": "string"
                },
                "ticker": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "stocks.AllTickersAPIResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "next_url": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/stocks.AllTickerStockInformation"
                    }
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
